export const COMMON_FETCH_CONFIG = 'COMMON_FETCH_CONFIG';
export const COMMON_FETCH_CONFIG_SUCCESS = 'COMMON_FETCH_CONFIG_SUCCESS';
export const COMMON_FETCH_CONFIG_FAIL = 'COMMON_FETCH_CONFIG_FAIL';

export const COMMON_REQUEST_UPLOAD = 'COMMON_REQUEST_UPLOAD';
export const COMMON_REQUEST_UPLOAD_SUCCESS = 'COMMON_REQUEST_UPLOAD_SUCCESS';
export const COMMON_REQUEST_UPLOAD_FAIL = 'COMMON_REQUEST_UPLOAD_FAIL';
