export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_REQUEST_LOGIN_SUCCESS = 'AUTH_REQUEST_LOGIN_SUCCESS';
export const AUTH_REQUEST_LOGIN_FAIL = 'AUTH_REQUEST_LOGIN_FAIL';

export const AUTH_REQUEST_ME = 'AUTH_REQUEST_ME';
export const AUTH_REQUEST_ME_SUCCESS = 'AUTH_REQUEST_ME_SUCCESS';
export const AUTH_REQUEST_ME_FAIL = 'AUTH_REQUEST_ME_FAIL';

export const AUTH_REQUEST_REFRESH_TOKEN = 'AUTH_REQUEST_REFRESH_TOKEN';
export const AUTH_REQUEST_REFRESH_TOKEN_SUCCESS = 'AUTH_REQUEST_REFRESH_TOKEN_SUCCESS';
export const AUTH_REQUEST_REFRESH_TOKEN_FAIL = 'AUTH_REQUEST_REFRESH_TOKEN_FAIL';

export const BEFORE_REQUEST_LOGIN = 'BEFORE_REQUEST_LOGIN';
export const SUCCESS_REQUEST_LOGIN = 'SUCCESS_REQUEST_LOGIN';
export const ERROR_REQUEST_LOGIN = 'ERROR_REQUEST_LOGIN';
export const FAIL_REQUEST_LOGIN = 'FAIL_REQUEST_LOGIN';

export const BEFORE_REQUEST_LOGOUT = 'BEFORE_REQUEST_LOGOUT';
export const SUCCESS_REQUEST_LOGOUT = 'SUCCESS_REQUEST_LOGOUT';
export const ERROR_REQUEST_LOGOUT = 'ERROR_REQUEST_LOGOUT';
export const FAIL_REQUEST_LOGOUT = 'FAIL_REQUEST_LOGOUT';

export const BEFORE_REQUEST_ME = 'BEFORE_REQUEST_ME';
export const SUCCESS_REQUEST_ME = 'SUCCESS_REQUEST_ME';
export const ERROR_REQUEST_ME = 'ERROR_REQUEST_ME';
export const FAIL_REQUEST_ME = 'FAIL_REQUEST_ME';

export const TOGGLE_FULL_PERMISSION = 'TOGGLE_FULL_PERMISSION';

export const RESET_LOGOUT_REQUEST = 'RESET_LOGOUT_REQUEST';

export const BEFORE_REQUEST_REFRESH_TOKEN = 'BEFORE_REQUEST_REFRESH_TOKEN';
export const SUCCESS_REQUEST_REFRESH_TOKEN = 'SUCCESS_REQUEST_REFRESH_TOKEN';
export const ERROR_REQUEST_REFRESH_TOKEN = 'ERROR_REQUEST_REFRESH_TOKEN';
