export const AUTH_REQUEST_LOGIN = 'AUTH_REQUEST_LOGIN';
export const AUTH_REQUEST_LOGIN_SUCCESS = 'AUTH_REQUEST_LOGIN_SUCCESS';
export const AUTH_REQUEST_LOGIN_FAIL = 'AUTH_REQUEST_LOGIN_FAIL';

export const AUTH_REQUEST_REGISTER = 'AUTH_REQUEST_REGISTER';
export const AUTH_REQUEST_REGISTER_SUCCESS = 'AUTH_REQUEST_REGISTER_SUCCESS';
export const AUTH_REQUEST_REGISTER_FAIL = 'AUTH_REQUEST_REGISTER_FAIL';

export const AUTH_REQUEST_ME = 'AUTH_REQUEST_ME';
export const AUTH_REQUEST_ME_SUCCESS = 'AUTH_REQUEST_ME_SUCCESS';
export const AUTH_REQUEST_ME_FAIL = 'AUTH_REQUEST_ME_FAIL';

export const AUTH_REQUEST_REFRESH_TOKEN = 'AUTH_REQUEST_REFRESH_TOKEN';
export const AUTH_REQUEST_REFRESH_TOKEN_SUCCESS = 'AUTH_REQUEST_REFRESH_TOKEN_SUCCESS';
export const AUTH_REQUEST_REFRESH_TOKEN_FAIL = 'AUTH_REQUEST_REFRESH_TOKEN_FAIL';

export const AUTH_REQUEST_LOGOUT = 'AUTH_REQUEST_LOGOUT';
export const AUTH_REQUEST_LOGOUT_SUCCESS = 'AUTH_REQUEST_LOGOUT_SUCCESS';
export const AUTH_REQUEST_LOGOUT_FAIL = 'AUTH_REQUEST_LOGOUT_FAIL';

export const TOGGLE_FULL_PERMISSION = 'TOGGLE_FULL_PERMISSION';

export const RESET_LOGOUT_REQUEST = 'RESET_LOGOUT_REQUEST';

export const BEFORE_REQUEST_REFRESH_TOKEN = 'BEFORE_REQUEST_REFRESH_TOKEN';
export const SUCCESS_REQUEST_REFRESH_TOKEN = 'SUCCESS_REQUEST_REFRESH_TOKEN';
export const ERROR_REQUEST_REFRESH_TOKEN = 'ERROR_REQUEST_REFRESH_TOKEN';
